www/config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */
use Cake\Http\Middleware\CsrfProtectionMiddleware;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 * Cache: Routes are cached to improve performance, check the RoutingMiddleware
 * constructor in your `src/Application.php` file to change this behavior.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::prefix('cp', function ($routes) {
    $routes->connect('/', ['controller' => 'Account', 'action' => 'login']);
    $routes->extensions(['json', 'pdf']);
    $routes->resources('Users');
    $routes->fallbacks('InflectedRoute');
});

Router::scope('/', function (RouteBuilder $routes) {
    // Register scoped middleware for in scopes.
    $routes->registerMiddleware('csrf', new CsrfProtectionMiddleware([
        'httpOnly' => true
    ]));

    /**
     * Apply a middleware to the current route scope.
     * Requires middleware to be registered via `Application::routes()` with `registerMiddleware()`
     */
    //$routes->applyMiddleware('csrf');

    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Account', 'action' => 'login']);
    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *
     * ```
     * $routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);
     * $routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);
     * ```
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->extensions(['json']);
    $routes->extensions(['pdf']);
    $routes->fallbacks(DashedRoute::class);
});

/**
 * If you need a different set of middleware or none at all,
 * open new scope and define routes there.
 *
 * ```
 * Router::scope('/api', function (RouteBuilder $routes) {
 *     // No $routes->applyMiddleware() here.
 *     // Connect API actions here.
 * });
 * ```
 */

www/src/Model/Table/ProjectTasksTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;
use Cake\Datasource\ConnectionManager;

class ProjectTasksTable extends Table {

    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('project_tasks');
        $this->addBehavior('Muffin/Footprint.Footprint');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');
		$this->addBehavior('Search.Search');
        $this->addBehavior('Neptune.DateFormat', [
			'fields' => ['target_date']
        ]);

    	$this->belongsTo('Projects', [
            'foreignKey' => 'project_id'
        ]);

        $this->belongsTo('AssignedUser', [
            'className' => 'Users',
            'foreignKey' => 'assigned_by'

        ]);

        $this->belongsTo('AssignedEmployee', [
            'className' => 'Employees',
            'foreignKey' => 'assigned_to'
        ]);

        $this->belongsTo('ResponsibleEmployee1', [
            'className' => 'Employees',
            'foreignKey' => 'responsible_1'
        ]);

        $this->belongsTo('ResponsibleEmployee2', [
            'className' => 'Employees',
            'foreignKey' => 'responsible_2'
        ]);

		$this->belongsTo('Tasks', [
            'foreignKey' => 'task_id'
        ]);
    }

    public function validationDefault(Validator $validator) {
        $validator->notEmpty('project_id', 'This field is compulsory');
        $validator->notEmpty('task_id', 'This field is compulsory');
        $validator->notEmpty('fees_type', 'This field is compulsory');
        $validator->notEmpty('days_require', 'This field is compulsory');
        $validator->notEmpty('list_order', 'This field is compulsory');
        $validator->notEmpty('percentage', 'This field is compulsory');
        $validator->notEmpty('fees', 'This field is compulsory');
        $validator->notEmpty('assigned_to', 'This field is compulsory');
        $validator->notEmpty('target_date', 'This field is compulsory');
        $validator->notEmpty('responsible_1', 'This field is compulsory');
        $validator->notEmpty('responsible_2', 'This field is compulsory');

        return $validator;
    }

    public function searchManager()
    {
        $searchManager = $this->behaviors()->Search->searchManager();

        $searchManager
            ->add('search', 'Search.Like', [
                'before' => true,
                'after' => true,
                'fieldMode' => 'OR',
                'comparison' => 'LIKE',
                'wildcardAny' => '*',
                'wildcardOne' => '?',
                'field' => ['Projects.project_no','Tasks.task']
            ]
        );
        return $searchManager;
    }

}

www/src/Controller/ProjectTasksController.php
<?php
namespace App\Controller;

use App\Controller\AppController;
use Cake\ORM\TableRegistry;
use Cake\Chronos\Chronos;
use Cake\I18n\Date;

class ProjectTasksController extends AppController
{
	public function initialize() {
		parent::initialize();
		 $this->loadComponent('Search.Prg', [
            'actions' => ['index']
        ]);
	}

	public function projects() {
		$this->set('title_for_layout', 'Projects');

        $query = $this->ProjectTasks->Projects
            ->find('search', ['search' => $this->request->getQueryParams()])
            ->where(['Projects.status' => 'Converted']);

        $this->paginate = ['contain'=>['Clients', 'ProjectTasks']];

		$this->set('projects', $this->paginate($query));
        $this->set('_serialize', ['projects']);
    }

	public function print($project_id) {
        $project = $this->ProjectTasks->Projects->get($project_id,[
            'contain'=>['Clients']
        ]);

        $this->set('project', $project);

        $projectTasks = $this->ProjectTasks->find()
            ->where(['ProjectTasks.project_id'=>$project_id])
            ->contain(['Projects'=>['Clients'],'Tasks','AssignedUser','AssignedEmployee', 'ResponsibleEmployee1'=>['Users'], 'ResponsibleEmployee2'=>['Users']]);


        // debug($projectTasks->toArray()); exit;

        $this->viewBuilder()->setClassName('CakePdf.Pdf');
        $this->viewBuilder()->options([
            'pdfConfig' => [
                'download' => false,
                'filename' => 'responsibility-sheet.pdf',
                'orientation' => 'landscape'
            ]
        ]);

		$this->set('projectTasks', $projectTasks);
    }


	public function index($project_id) {
        $project = $this->ProjectTasks->Projects->get($project_id,[
            'contain'=>['Clients']
        ]);
        $this->set('title_for_layout', 'Documents - ' . $project->project_with_client);

		if($this->Auth->user('id') == 1 ){
			$query = $this->ProjectTasks
			    ->find('search', ['search' => $this->request->getQueryParams()])
                ->where(['ProjectTasks.project_id' => $project_id]);
		}else{
			$query = $this->ProjectTasks
			    ->find('search', ['search' => $this->request->getQueryParams()])
			    ->where([
                    'ProjectTasks.assigned_to' =>$this->Auth->user('id'),
                    'ProjectTasks.project_id' => $project_id
                ]);
		}
		$this->paginate = ['contain'=>['Projects'=>['Clients'],'Tasks','AssignedUser','AssignedEmployee', 'ResponsibleEmployee1', 'ResponsibleEmployee2'],'order'=>['ProjectTasks.list_order'=>'ASC']];

		$employee = TableRegistry::get('Employees');
		$employees = $employee->find('list');

		$this->set(compact('employees'));
		$this->set('projectTasks', $this->paginate($query));
        $this->set('_serialize', ['projectTasks']);
    }

	public function edit($id) {
		$this->set('title_for_layout', 'Project Tasks');

        $projectTask = $this->ProjectTasks->get($id, ['contain'=>['Projects'=>['Clients']]]);

        if($this->request->is(['patch','post','put'])) {
			$projectTask = $this->ProjectTasks->patchEntity($projectTask, $this->request->getData());

			if($this->ProjectTasks->save($projectTask)) {
				$this->Flash->success('The Project Tasks has been saved');
				return $this->redirect(['action'=>'index', $projectTask->project_id]);
			} else {
				$this->Flash->error('The Project Tasks could not be saved try again');
			}
		}

		$employees = TableRegistry::get('Employees')->find('list');
        $this->set(compact('projectTask', 'employees'));
	}

	public function delete($id=null) {
		$this->request->allowMethod(['post','delete']);
		$projectTasks=$this->ProjectTasks->get($id);
		if($this->ProjectTasks->delete($projectTasks)) {
			$this->Flash->success('The Project Tasks has been deleted');
		}
		else {
			$this->Flash->error('The Project Tasks could not be deleted try again');
		}
		return $this->redirect(['action'=>'index']);
	}

	public function assign($taskId=null) {
		$this->set('title_for_layout', 'Assign');
        $projectTask = $this->ProjectTasks->get($taskId, ['contain'=>['Projects'=>['Clients']]]);
		$employees = TableRegistry::get('Employees')->find('list');
		$this->set(compact('projectTask','employees'));

		$User = TableRegistry::get('Users');
		$users = $User->get($this->Auth->user('id'));

        if ($this->request->is('post') || $this->request->is('put')) {
			$projectTask = $this->ProjectTasks->patchEntity($projectTask, $this->request->getData());
            $projectTask->assigned_by = $users['id'];
            $projectTask->assigned_datetime = date('Y-m-d H:i:s');

            if($this->ProjectTasks->save($projectTask)) {
                $this->Flash->success('The Project Tasks has been Assign');
                return $this->redirect(['action'=>'index', $projectTask->project_id]);
            } else {
                $this->Flash->error('The Project Tasks could not be Assign try again');
            }
        }
    }

	public function done($taskId=null, $page=1) {
        $projectTask = $this->ProjectTasks->get($taskId, ['contain'=>['Projects']]);

        $projectTask->done_by = $this->Auth->user('id');
        $projectTask->done_datetime = date('Y-m-d H:i:s');

        $this->ProjectTasks->save($projectTask);

        $Invoices = TableRegistry::get('Invoices');

        $data['invoice_date'] = date('d/m/Y');
        $data['project_id'] = $projectTask->project_id;
        $data['amount_before_tax'] = $projectTask->fees;

        $data['invoice_details'][0]['project_task_id'] = $projectTask->id;
        $data['invoice_details'][0]['task_id'] = $projectTask->task_id;
        $data['invoice_details'][0]['service'] = $projectTask->service;
        $data['invoice_details'][0]['description'] = $projectTask->description;

        $data['invoice_details'][0]['fees'] = $projectTask->fees;
        $data['invoice_details'][0]['discount'] = 0;
        $data['invoice_details'][0]['dis_amt'] = 0;

        $data['invoice_details'][0]['cgst_rate'] = $projectTask->project->cgst;
        $data['invoice_details'][0]['cgst_amount'] = ($projectTask->fees * $projectTask->project->cgst) / 100;
        $data['invoice_details'][0]['sgst_rate'] = $projectTask->project->sgst;
        $data['invoice_details'][0]['sgst_amount'] = ($projectTask->fees * $projectTask->project->sgst) / 100;
        $data['invoice_details'][0]['igst_rate'] = $projectTask->project->igst;
        $data['invoice_details'][0]['igst_amount'] = ($projectTask->fees * $projectTask->project->igst) / 100;
        $data['invoice_details'][0]['amount'] = round($data['invoice_details'][0]['fees'] + $data['invoice_details'][0]['cgst_amount'] + $data['invoice_details'][0]['sgst_amount'] + $data['invoice_details'][0]['igst_amount']);


        $data['total_amount'] = round($data['invoice_details'][0]['amount']);
        $data['amount_in_words'] = $this->amountToWords($data['total_amount']);


        $invoice = $Invoices->newEntity();
        $invoice = $Invoices->patchEntity($invoice, $data);
        $Invoices->save($invoice);

        $invoicesController =  new \App\Controller\InvoicesController();
        $invoicesController->generateInvoice($invoice->id);

        $this->Flash->success('The Project Tasks has been Done');
        return $this->redirect(['action'=>'index', $projectTask->project_id]);
    }
}

www/src/Template/ProjectTasks/pdf/print.ctp
<?php //debug($projecttasks->toArray()); exit; ?>
<html>
    <head>
		<style>
			body {
				font-family: sans-serif;
				font-size: 11px;
			}
			table {
				width: 100%;
				border-collapse: collapse;
			}
			table, th, td {
				border: 1px solid #BFBFBF;
				padding: 5px;
				vertical-align: top;
			}
			th {
				align: center;
				vertical-align: middle;
			}

			tr.rejected td, tr.rejected th {
				text-decoration: line-through;
			}

			.color {
				background-color: #E5E5E5;
			}

			h3, hr {
				padding :0;
				margin :0;
			}
		/** Define the margins of your page **/
			@page {
        		header: html_myHeader;
        		footer: html_myFooter;
				margin-top: 3cm;
			}

			div.page-break {
        		page-break-before: always;
		    }
		</style>
	</head>
	<body>
		<htmlpageheader name="myHeader" style="display:none">
			<h2 align="center">Dominion</h2>
			<p align="center"><strong>PROJECT RESPONSIBILITY CHART for <?= $project->project_with_client ?> as on <?= date('d/m/Y H:i a') ?></strong></p>
			<hr />
    	</htmlpageheader>

		<htmlpagefooter name="myFooter" style="display:none">
			<table width="100%" border="0">
				<tr>
					<td width="70%" align="center" style="font-weight: bold; font-style: italic;">
						&nbsp;
					</td>
					<td align="right" style="font-weight: bold; font-style: italic;">
						Page {PAGENO}/{nbpg}
					</td>
				</tr>
			</table>
		</htmlpagefooter>
		<table>
			<thead>
				<tr class="color">
					<th width="3%">Sr No</th>
					<th>Particulars / Project Stage</th>
                    <th width="8%">Allotted Date</th>
                    <th width="8%">Target Date</th>
                    <th width="8%">Completion Date</th>
					<th width="8%">Responsible Person 1</th>
                    <th width="8%">Email 1</th>
                    <th width="8%">Mobile No 1</th>
					<th width="8%">Responsible Person 2</th>
                    <th width="8%">Email 2</th>
                    <th width="8%">Mobile No 2</th>
				</tr>
			</thead>
			<tbody>
            <?php
                foreach($projectTasks as $i => $projectTask) {
            ?>
            <tr>
                <td><?= ($i+1) ?></td>
                <td>
                    <strong><?= $projectTask->task->task ?></strong><br />
                    <?= $projectTask->description ?>
                </td>
                <td><?= !empty($projectTask->assigned_datetime) ? $projectTask->assigned_datetime->format('d/m/Y') : '' ?></td>
                <td><?= $projectTask->target_date ?></td>
                <td><?= !empty($projectTask->done_datetime) ? $projectTask->done_datetime->format('d/m/Y') : '' ?></td>
                <td><?= !empty($projectTask->responsible_employee1) ? $projectTask->responsible_employee1->name : '' ?></td>
                <td><?= !empty($projectTask->responsible_employee1) ? $projectTask->responsible_employee1->user->email : '' ?></td>
                <td><?= !empty($projectTask->responsible_employee1) ? $projectTask->responsible_employee1->user->mobile : '' ?></td>
                <td><?= !empty($projectTask->responsible_employee1) ? $projectTask->responsible_employee2->name : '' ?></td>
                <td><?= !empty($projectTask->responsible_employee1) ? $projectTask->responsible_employee2->user->email : '' ?></td>
                <td><?= !empty($projectTask->responsible_employee1) ? $projectTask->responsible_employee2->user->mobile : '' ?></td>
            </tr>
			<?php } ?>
			</tbody>
		</table>
	</body>
</html>