www/config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */
use Cake\Http\Middleware\CsrfProtectionMiddleware;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 * Cache: Routes are cached to improve performance, check the RoutingMiddleware
 * constructor in your `src/Application.php` file to change this behavior.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::prefix('cp', function ($routes) {
    $routes->connect('/', ['controller' => 'Account', 'action' => 'login']);
    $routes->extensions(['json', 'pdf']);
    $routes->resources('Users');
    $routes->fallbacks('InflectedRoute');
});

Router::scope('/', function (RouteBuilder $routes) {
    // Register scoped middleware for in scopes.
    $routes->registerMiddleware('csrf', new CsrfProtectionMiddleware([
        'httpOnly' => true
    ]));

    /**
     * Apply a middleware to the current route scope.
     * Requires middleware to be registered via `Application::routes()` with `registerMiddleware()`
     */
    //$routes->applyMiddleware('csrf');

    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Account', 'action' => 'login']);
    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *
     * ```
     * $routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);
     * $routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);
     * ```
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->extensions(['json']);
    $routes->extensions(['pdf']);
    $routes->fallbacks(DashedRoute::class);
});

/**
 * If you need a different set of middleware or none at all,
 * open new scope and define routes there.
 *
 * ```
 * Router::scope('/api', function (RouteBuilder $routes) {
 *     // No $routes->applyMiddleware() here.
 *     // Connect API actions here.
 * });
 * ```
 */

www/src/Model/Table/MeetingReportsTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;
use Cake\Datasource\ConnectionManager;
use Cake\ORM\TableRegistry;


class MeetingReportsTable extends Table
{
   
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('meeting_reports');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->addBehavior('Search.Search');
        $this->addBehavior('Timestamp');

        $this->addBehavior('Neptune.DateFormat', [
			'fields' => ['meeting_date']
        ]);
        $this->addBehavior('Neptune.TimeFormat', [
			'fields' => ['time']
        ]);

        $this->belongsTo('Employees', [
            'foreignKey' => 'employee_id',
        ]);
        $this->belongsTo('Projects', [
            'foreignKey' => 'project_id',
        ]);
        $this->hasMany('MeetingReportImages', [
            'foreignKey' => 'meeting_report_id',
            'dependent' => true,
            'cascadeCallbacks' => true,
            'saveStrategy'=>'replace'
        ]);
        $this->hasMany('MeetingReportStakeholders', [
            'foreignKey' => 'meeting_report_id',
            'dependent' => true,
            'cascadeCallbacks' => true,
            'saveStrategy'=>'replace'
        ]);
        $this->hasMany('MeetingReportVisitors', [
            'foreignKey' => 'meeting_report_id',
            'dependent' => true,
            'cascadeCallbacks' => true,
            'saveStrategy'=>'replace'
        ]);
    }

   
    public function validationDefault(Validator $validator)
    {
        $validator
            ->nonNegativeInteger('id')
            ->allowEmptyString('id', null, 'create');     

        $validator          
            ->notEmpty('meeting_date');

        $validator           
            ->notEmpty('meeting_time');

        $validator           
            ->notEmpty('employee_id'); 

        $validator           
            ->notEmpty('project_id');       

      

        return $validator;
    }

    public function getNo($project_id = null, $project_no){
      

        $conn=ConnectionManager::get('default');
		
		$strSql="
            SELECT IFNULL(MAX(RIGHT(meeting_no, 4)),0) + 1 AS max_id
			FROM meeting_reports
            WHERE project_id = '" . $project_id . "'";

        $result=$conn->execute($strSql)->fetchAll('assoc');
        $code = $project_no."/M".str_pad($result[0]['max_id'],4,'0',STR_PAD_LEFT);
        return $code;
     }


    

    public function searchManager()
    {
        $searchManager = $this->behaviors()->Search->searchManager();

        $searchManager            
            ->add('search', 'Search.Like', [
                'before' => true,
                'after' => true,
                'fieldMode' => 'OR',
                'comparison' => 'LIKE',
                'wildcardAny' => '*',
                'wildcardOne' => '?',
                'field' => ['meeting_no', 'Employees.name']
            ]
        );
        return $searchManager;
    }    

   
}

www/src/Controller/MeetingReportsController.php
<?php
namespace App\Controller;

use App\Controller\AppController;
use Cake\ORM\TableRegistry;
use Cake\I18n\Time;


class MeetingReportsController extends AppController
{
    public function initialize() {
		parent::initialize();
		$this->loadComponent('Search.Prg', [
            'actions' => ['index', 'list']
        ]);
	}
   
    public function index()
    {
       $this->set('title', 'Meeting Reports');
       $query = $this->MeetingReports
        ->find('search',['search'=>$this->request->getQueryParams()])
        ->contain(['Employees', 'Projects'=>['Clients'],'MeetingReportImages', 'MeetingReportStakeholders'=>['Stakeholders'], 'MeetingReportVisitors']);
        $this->paginate = ['order'=>['id'=>'DESC']];
        $this->set('meetingReports', $this->paginate($query));
        $this->set('_serialize', ['meetingReport']);
        
    }

    public function edit($id = null)
    {
        $this->set('title', 'Meeting Reports');
        if(empty($id)){
            $meetingReport = $this->MeetingReports->newEntity();
            $meetingReport->meeting_date = date('d/m/Y');
        } else{
            $meetingReport = $this->MeetingReports->get($id, [
                'contain' => ['Employees', 'Projects'=>['Clients'],'MeetingReportImages', 'MeetingReportStakeholders'=>['Stakeholders'], 'MeetingReportVisitors']]);

        }
       
        if ($this->request->is(['patch', 'post', 'put'])) {
            $data = $this->request->getData();	
            $meetingReport = $this->MeetingReports->patchEntity($meetingReport, $this->request->getData());
            if($meetingReport->isNew()){
                $project = $this->MeetingReports->Projects->get($meetingReport->project_id);				
				$meetingReport->meeting_no = $this->MeetingReports->getNo($meetingReport->project_id, $project->project_no);

            }
            if(!empty($meetingReport->meeting_time)){					
                $meetingReport->meeting_time = Time::createFromFormat('Y-m-d H:i a', date('Y-m-d').' '.$data['meeting_time']);
                } else {
                    $this->Flash->error('Visit Time is require');
                }    
            if ($this->MeetingReports->save($meetingReport)) {
                $this->generateMeetingReport($meetingReport->id);
                $this->Flash->success(__('The meeting report has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The meeting report could not be saved. Please, try again.'));
        }
        if(empty($meetingReport['meeting_report_stakeholders'])){
            $meetingReport['meeting_report_stakeholders'] = [];
        }
        if(empty($meetingReport['meeting_report_images'])){
            $meetingReport['meeting_report_images'] = [];
        }
        if(empty($meetingReport['meeting_report_visitors'])){
            $meetingReport['meeting_report_visitors'] = [];
        }
        $Stakeholders = TableRegistry::get('stakeholders');
		$stakeholders = $Stakeholders->find('list');
        $employees = $this->MeetingReports->Employees->find('list');
        $projects = $this->MeetingReports->Projects->find('list', ['keyField'=>'id','valueField'=>'project_with_client'])->where(['status'=>'Converted'])->contain('Clients');
        $this->set(compact('meetingReport', 'employees', 'projects', 'stakeholders'));
    }
  
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $meetingReport = $this->MeetingReports->get($id);
        if ($this->MeetingReports->delete($meetingReport)) {
            $this->Flash->success(__('The meeting report has been deleted.'));
        } else {
            $this->Flash->error(__('The meeting report could not be deleted. Please, try again.'));
        }

        return $this->redirect(['action' => 'index']);
    }
    public function generateMeetingReport($id) {
        $meetingReport = $this->MeetingReports->get($id, [
            'contain' => ['Employees', 'Projects'=>['Clients'],'MeetingReportImages', 'MeetingReportStakeholders'=>['Stakeholders'], 'MeetingReportVisitors']]);

        $CakePdf = new \CakePdf\Pdf\CakePdf();
		$CakePdf->template('meeting_report', 'default');
        // debug($meetingReport); exit;

        $this->viewVars = ['meetingReport'=>$meetingReport];
		$this->viewBuilder()->setLayout('pdf');
      

		$CakePdf->viewVars($this->viewVars);      
		$pdf = $CakePdf->output();
       	$pdf = $CakePdf->write(WWW_ROOT . 'files' . DS . 'meeting_report'  . DS . 'meeting_report-' . $meetingReport->meeting_no . '.pdf');
	}
}

www/src/Template/MeetingReports/edit.ctp
<?php
    use Cake\Core\Configure;
?>
<script>	
    indexs = 0;
    indexs = <?php echo count($meetingReport['meeting_report_images'])+1; ?>;
    k = 0;
    k = <?php echo count($meetingReport['meeting_report_stakeholders'])+1; ?>;
    j = 0;
    j = <?php echo count($meetingReport['meeting_report_visitors'])+1; ?>;

    function addRows(row, k) {
        html = "<tr id='rowss_"+k+"'>";
            html += "<td><a href='javascript:void(0); removeRows("+k+");'><i class='fa fa-minus'></i></a></td>";
            html += "<td><div class='form-group'>";
            html += "<td><input type='hidden' id='meeting-report-stakeholders-" + k + "-stakeholder-id'  name='meeting_report_stakeholders[" + k + "][stakeholder_id]' value=" + row.stakeholder_id + ">"+ row.stakeholder.contractor+"</td>";          
            html += "</div></td>";
        html += "</tr>";
        $(html).appendTo("#stakeholdersData tbody");       
        k++;
    
    } 
	

	
    function projectChange(i){
        var id = $("#project-id").val();       
        $.getJSON('/Projects/getStakeholders/' + id, function(data){
            console.log(data.projects.project_stakeholders)
            data.projects.project_stakeholders.forEach(function(row, index) {
                    addRows(row, index);
            });

        });
	} 



    function add_rows() {
		html = "<tr id='rowws_"+j+"'>";
			html += "<td><a href='javascript:void(0); remove_rows("+j+");'><i class='fa fa-minus'></i></a></td>";			
			html += "<td><div class='form-group'><input type='text' id='meeting-report-visitors-"+j+"-name'  class='form-control qt' name='meeting_report_visitors["+j+"][name]'></div></td>";
			html += "<td><div class='form-group'><input type='text' id='meeting-report-visitors-"+j+"-email'  class='form-control rt' name='meeting_report_visitors["+j+"][email]'></div></td>";		
		html += "</tr>";
		$(html).appendTo("#visitorsData tbody");
		j++;		
	}
    function addRow(){       
        html ="<tr id='rows_"+indexs+"'>";
            html += "<td><a href='javascript:void(0); removeRow("+indexs+");'><i class='fa fa-minus'></i></a></td>";          
            html += "<td><input type='file' id='meeting-report-images-"+indexs+"-image' name='meeting_report_images["+indexs+"][image]' class='form-control'></td>";
            html += "<td><input type='hidden' id='meeting-report-images-"+indexs+"-image-dir' name='meeting_report_images["+indexs+"][image.dir]' class='form-control'></td>";
          
         html += "</tr>";
        html2 ="<tr id='second_rows_"+indexs+"'>";
            html2 +="<td>&nbsp; </td>";
            html2 +="<td colspan='12'><input id='meeting-report-images-"+indexs+"-remarks' name='meeting_report_images["+indexs+"][remarks]' class='form-control'  placeholder='Remarks'></td>";
        html2 += "</tr>";
        $(html).appendTo("#tblDetail tbody");
        $(html2).appendTo("#tblDetail tbody");
        indexs++;
    }  
	
    function removeRow(i) {
		$("#rows_"+i).detach();
		$("#second_rows_"+i).detach();
		indexs--;
	}
    function removeRows(k) {
        $("#rowss_"+k).detach();
        k--;		
    }
    
	function remove_rows(j) {
		$("#rowws_"+j).detach();
		j--;	
	}
   
</script>
<?= $this->Form->create($meetingReport,['type'=>'file','novalidate'=>true]) ?>
<div class="box box-block bg-white">
	<div class="clearfix mb-1">
		<h5 class="float-xs-left"><?= $title; ?></h5>
	</div>
    <fieldset>
		<div class="row">
			<div class="col-md-4">
				<?php echo $this->Form->hidden('id'); ?>
				<?php echo $this->Form->control('meeting_no', ['readonly'=>true]); ?>
			</div>
			<div class="col-md-4">

				<?php echo $this->N->datepicker('meeting_date',['required'=>true]); ?>
			</div>
			<div class="col-md-4">
                <?php if(empty($meetingReport->id)){
                   echo  $this->N->select2('meeting_time', ['options'=>Configure::read('time'), 'empty'=>true]);
                } else{
                    echo $this->Form->control('meeting_time', [ 'type'=>'text', 'value'=>$meetingReport->meeting_time->format('g:i a'),'readonly'=>true]);
                } ?>
        	</div>

		</div>
		<div class="row">
            <div class="col-md-4">
				<?php echo $this->N->select2('employee_id', ['options'=>$employees , 'empty'=>'---']); ?>
			</div>
			<div class="col-md-4">
				<?php echo $this->N->select2('project_id', ['options'=>$projects , 'empty'=>'---', 'onChange'=>'return projectChange()']); ?>
			</div>

		</div>
		<div class="row">
			<div class="col-md-12">
				<?php echo $this->Form->control('report'); ?>
			</div>
		</div>
		</fieldset><br>
</div>
<div class="box box-block bg-white">
    <div class="row">
        <div class="col-md-12">
            <legend><span>Meeting Reports Images</span></legend>
            <table class="table  table-hover" id="tblDetail">
                <thead>
                    <tr>
                        <th>&nbsp;</th>                       
                        <th>Image</th>

                    </tr>
                </thead>
                <tbody>
                <?php
                    if(!empty($meetingReport['meeting_report_images'])) {
                        foreach($meetingReport['meeting_report_images'] as $i=>$image) {
                ?>
                    <tr id="rows_<?php echo $i;?>">
                        <td><a href='javascript:void(0); removeRow("<?php echo $i;?>");'><i class='fa fa-minus'></i></a></td>
                        <td>
                            <?php
                                echo $this->Form->input('meeting_report_images.'.$i.'.id',['type'=>'hidden']);                    
                                                        
                                if(!empty($image->id)){
                                    echo $this->Form->hidden('meeting_report_images.'.$i.'.image',['value'=>$image->image]);
                                    echo $this->Html->image('/files/meetingReportimages/image/'.$image->image_dir.'/'.$image->image, array('width'=>'150px', 'hieght'=>'150px'));
                                } else {
                                    echo $this->Form->control('meeting_report_images.'.$i.'.image',['value'=>$image->image, 'type'=>'file', 'label'=>false]);
                                }

                            ?>
                        </td>
                        <td><?php echo $this->Form->hidden('meeting_report_images.'.$i.'.image_dir',[ 'value'=>$image->image_dir]);?></td>
                    </tr>
                    <tr id="second_rows_<?php echo $i;?>">
                        <td>&nbsp;</td>
                        <td colspan="3"><?php echo $this->Form->control('meeting_report_images.'.$i.'.remarks', ['type'=>'text', 'label'=>false, 'class'=>'span12' , 'value'=>$image->remarks, 'placeholder'=>'Remarks']);?></td>
                    </tr>

                <?php  }} ?>
                </tbody>
                <tfoot>
                    <tr>
                        <td><a href="javascript:void(0); addRow();">+</a></td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
        <legend><span> Stake Holders </span></legend>
		<table class="table table-striped table-condense table-responsive" id="stakeholdersData">
			<thead>
				<tr>
					<th>&nbsp;</th>
					<th style="">Stake Holders </th>					
				</tr>
			</thead>
			<tbody>
			<?php
				if(!empty($meetingReport['meeting_report_stakeholders'])) {
					foreach($meetingReport['meeting_report_stakeholders'] as $i=>$stakeholder) {
			?>
			<tr id="rowss_<?php echo $i;?>">
				<td><a href='javascript:void(0); removeRows("<?php echo $i;?>");'><i class='fa fa-minus'></i></a></td>
				<td>
					<?php
						echo $this->Form->input('meeting_report_stakeholders.'.$i.'.id',['type'=>'hidden']);
						echo $this->N->select2('meeting_report_stakeholders.'.$i.'.stakeholder_id',array('label'=>false,'options'=>$stakeholders,'empty'=>'(Choose One)'));
					?>
				</td>			
			</tr>
			<?php  }} ?>
			</tbody>			
		</table>	
        </div>		        
	
        <div class="col-md-6">
        <legend><span> Visitors Details</span></legend>
        <table class="table table-striped table-condense table-responsive" id="visitorsData">
            <thead>
                <tr>
                    <th>&nbsp;</th>
                    <th>Name</th>
                    <th>Email</th>
                  
                </tr>
            </thead>
            <tbody>
            <?php
                if(!empty($meetingReport['meeting_report_visitors'])) {
                    foreach($meetingReport['meeting_report_visitors'] as $i=>$visitor) {
            ?>
                <tr id="rowws_<?php echo $i;?>">
                    <td><a href='javascript:void(0); remove_rows("<?php echo $i;?>");'><i class='fa fa-minus'></i></a></td>
                    <td>
                        <?php
                            echo $this->Form->input('meeting_report_visitors.'.$i.'.id',['type'=>'hidden']);
                            echo $this->Form->control('meeting_report_visitors.'.$i.'.name',array('label'=>false));
                        ?>
                    </td>
                    <td><?php echo $this->Form->control('meeting_report_visitors.'.$i.'.email',['label'=>false,]);?></td>
                </tr>
            <?php  }} ?>
            </tbody>
            <tfoot>
                <tr>
                    <td><a href="javascript:void(0); add_rows();">+</a></td>
                    <td colspan="2"></td>
                </tr>              
            </tfoot>
        </table> 
        </div>            
    </div>
    <fieldset>
		<div class="row pull-right">
			<div class="col-md-12">
				<?= $this->N->cancelLink(['action'=>'index']); ?>
				<button class="btn btn-primary">Save</button>
			</div>
		</div>
	</fieldset><br>
</div>

<?= $this->Form->end() ?>

www/src/Template/MeetingReports/index.ctp
<div class="box box-block bg-white">
	<div class="clearfix mb-1">
		<h5 class="float-xs-left"><?= $title; ?></h5>
	</div>
    <?php echo $this->Form->create(null, ['class'=>'form-inline','valueSources' => 'query','id'=>'SearchForm']); ?>
        <?php echo $this->Form->input('search',['placeholder'=>'Search','label'=>false]); ?>		
        <?php echo $this->Form->button('Search', ['class'=>'btn btn-bordered-info']); ?>
        <?php echo $this->Html->link('Reset', ['action' => 'index'],['class'=>'btn btn-primary']); ?>
        <?php echo $this->Form->end(); ?>    
	<script>
		$(document).ready(function(){
			$("#SearchForm").one("submit", function(e) {
				e.preventDefault();
				$.post('meetingReports', $('#SearchForm').serialize()).done(function(data){
					NProgress.start();
					$("#ajaxDiv").empty().append(data);
					NProgress.done();
				});;
			});			
		});
	</script>
</div>
<div class="box box-block bg-white">
    <div class="clearfix mb-1">
		<div class="float-xs-right">
			<?= $this->N->addLink(array('action'=>'edit')); ?>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<div class="table-responsive">
				<table class="table table-hover">
                    <thead>
                        <tr>
                            <th scope="col"><?= $this->Paginator->sort('meeting_no')?></th>	
							<th scope="col"><?= $this->Paginator->sort('meeting_date')?></th>	
							<th scope="col"><?= $this->Paginator->sort('meeting_time')?></th>						
							<th scope="col"><?= $this->Paginator->sort('employee_id')?></th>
							<th scope="col"><?= $this->Paginator->sort('project_id')?></th>
                            <th scope="col" width="15%"><?= $this->Paginator->sort('Actions') ?></th>
				        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($meetingReports as $meetingReport): ?>
                        <tr>
                            <td><?= $meetingReport->meeting_no?></td>
							<td><?= $meetingReport->meeting_date?></td>
							<td><?= $meetingReport->meeting_time->format('h:i a') ?></td>
							<td><?= $meetingReport->employee->name?></td>
							<td><?= $meetingReport->project->project_with_client?></td>
                            <td class="actions">
                                <?= $this->N->editLink(['action' => 'edit', $meetingReport->id]); ?>
								<?= $this->Html->link('Print', '/files' .  DS . 'meeting_report' . DS . 'meeting_report-' . $meetingReport->meeting_no . '.pdf' ,['class'=>'btn btn-info btn-sm', 'target'=>'_blank']); ?>
								<?= $this->N->deleteLink(['action' => 'delete', $meetingReport->id]); ?>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
				</table>
			</div>
       </div>
	</div>
</div>	
<?php echo $this->element('Neptune.pagination'); ?>