www/config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */
use Cake\Http\Middleware\CsrfProtectionMiddleware;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 * Cache: Routes are cached to improve performance, check the RoutingMiddleware
 * constructor in your `src/Application.php` file to change this behavior.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::prefix('cp', function ($routes) {
    $routes->connect('/', ['controller' => 'Account', 'action' => 'login']);
    $routes->extensions(['json', 'pdf']);
    $routes->resources('Users');
    $routes->fallbacks('InflectedRoute');
});

Router::scope('/', function (RouteBuilder $routes) {
    // Register scoped middleware for in scopes.
    $routes->registerMiddleware('csrf', new CsrfProtectionMiddleware([
        'httpOnly' => true
    ]));

    /**
     * Apply a middleware to the current route scope.
     * Requires middleware to be registered via `Application::routes()` with `registerMiddleware()`
     */
    //$routes->applyMiddleware('csrf');

    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Account', 'action' => 'login']);
    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *
     * ```
     * $routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);
     * $routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);
     * ```
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->extensions(['json']);
    $routes->extensions(['pdf']);
    $routes->fallbacks(DashedRoute::class);
});

/**
 * If you need a different set of middleware or none at all,
 * open new scope and define routes there.
 *
 * ```
 * Router::scope('/api', function (RouteBuilder $routes) {
 *     // No $routes->applyMiddleware() here.
 *     // Connect API actions here.
 * });
 * ```
 */

www/src/Model/Table/DailyTasksTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;
use Cake\Datasource\ConnectionManager;

class DailyTasksTable extends Table {

    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->addBehavior('Muffin/Footprint.Footprint');

        $this->addBehavior('Timestamp');
		$this->addBehavior('Search.Search');
        $this->addBehavior('Neptune.DateFormat', [
			'fields' => ['due_date', 'done_date']
        ]);

    	$this->belongsTo('Projects', [
            'foreignKey' => 'project_id'
        ]);

    	$this->belongsTo('Activities', [
            'foreignKey' => 'activity_id'
        ]);

        $this->belongsTo('AssignedEmployee', [
            'className' => 'Employees',
            'foreignKey' => 'assigned_to'
        ]);

        $this->belongsTo('CreatedEmployee', [
            'className' => 'Employees',
            'foreignKey' => 'created_by'
        ]);
    }

    public function validationDefault(Validator $validator) {
        $validator
            ->notEmpty('task', 'This field is compulsory');
        $validator
            ->notEmpty('assigned_to', 'This field is compulsory');
         $validator
            ->notEmpty('due_date', 'This field is compulsory');

        return $validator;
    }

    public function searchManager()
    {
        $searchManager = $this->behaviors()->Search->searchManager();

        $searchManager
            ->add('search', 'Search.Like', [
                'before' => true,
                'after' => true,
                'fieldMode' => 'OR',
                'comparison' => 'LIKE',
                'wildcardAny' => '*',
                'wildcardOne' => '?',
                'field' => ['task','description']
            ]
        );
        return $searchManager;
    }

}

www/src/Controller/DailyTasksController.php
<?php
namespace App\Controller;

use App\Controller\AppController;
use Cake\ORM\TableRegistry;
use Cake\Chronos\Chronos;
use Cake\I18n\Date;

class DailyTasksController extends AppController
{
	public function initialize() {
		parent::initialize();
		 $this->loadComponent('Search.Prg', [
            'actions' => ['index']
        ]);
	}

	public function index() {
		$this->set('title_for_layout', 'Project Tasks');

		if($this->Auth->user('id') == 1 ) {
			$query = $this->DailyTasks
               ->find('search', ['search' => $this->request->getQueryParams()]);
		} else {
			$query = $this->DailyTasks
              ->find('search', ['search' => $this->request->getQueryParams()])
              ->where([
                  'OR' => [
                    'DailyTasks.assigned_to' =>$this->Auth->user('id'),
                    'DailyTasks.created_by' =>$this->Auth->user('id')
                  ]
                ]);
		}
		$this->paginate = ['contain'=>['Projects'=>['Clients'], 'Activities', 'AssignedEmployee','CreatedEmployee'],'order'=>['DailyTasks.due_date'=>'DESC']];

		$this->set('dailyTasks', $this->paginate($query));
        $this->set('_serialize', ['dailyTasks']);
    }

	public function edit($id=null) {
		$this->set('title_for_layout', 'Project Tasks');

		if(empty($id)) {
			$dailyTask = $this->DailyTasks->newEntity();
		} else {
			$dailyTask = $this->DailyTasks->get($id, [
                'contain' => ['Projects'=>['Clients'], 'Activities', 'AssignedEmployee','CreatedEmployee']
            ]);
		}

		if($this->request->is(['patch','post','put'])) {
			$dailyTask = $this->DailyTasks->patchEntity($dailyTask, $this->request->getData());

			if($this->DailyTasks->save($dailyTask)) {
				$this->Flash->success('The Tasks has been saved');
				return $this->redirect(['action'=>'index']);
			} else {
				$this->Flash->error('The Tasks could not be saved try again');
			}
		}
        $projects = $this->DailyTasks->Projects->find('list')->contain(['Clients']);
        $employees = $this->DailyTasks->AssignedEmployee->find('list');
        $activities = $this->DailyTasks->Activities->find('list');
        $this->set(compact('dailyTask', 'projects', 'employees', 'activities'));
	}

	public function progress($id=null) {
		$this->set('title_for_layout', 'Project Tasks');

		if(empty($id)) {
			$dailyTask = $this->DailyTasks->newEntity();
		} else {
            $dailyTask = $this->DailyTasks->get($id, [
                'contain' => ['Projects'=>['Clients'], 'Activities', 'AssignedEmployee','CreatedEmployee']
            ]);
		}

		if($this->request->is(['patch','post','put'])) {
			$dailyTask = $this->DailyTasks->patchEntity($dailyTask, $this->request->getData());

            if($dailyTask->status == 'Done') {
                $dailyTask->done_date = date('d/m/Y');
            } else {
                $newTask = $this->DailyTasks->newEntity();
                $newTask->project_id = $dailyTask->project_id;
                $newTask->activity_id = $dailyTask->activity_id;
                $newTask->assigned_to = $dailyTask->assigned_to;

                $newDueDate = \DateTime::createFromFormat('d/m/Y', $dailyTask->due_date)->add(new \DateInterval('P1D'));
                $newTask->due_date = $newDueDate->format('d/m/Y');

                $newTask->done_date = $dailyTask->done_date;
            }

            if($this->DailyTasks->save($dailyTask)) {
                if(isset($newTask)) {
                    $this->DailyTasks->save($newTask);
                }
				$this->Flash->success('The Tasks has been saved');
				return $this->redirect(['action'=>'index']);
			} else {
				$this->Flash->error('The Tasks could not be saved try again');
			}
		}
        $projects = $this->DailyTasks->Projects->find('list')->contain(['Clients']);
        $employees = $this->DailyTasks->AssignedEmployee->find('list');
        $activities = $this->DailyTasks->Activities->find('list');
        $this->set(compact('dailyTask', 'projects', 'employees', 'activities'));
	}

	public function delete($id=null) {
		$this->request->allowMethod(['post','delete']);

        $dailyTask = $this->DailyTasks->get($id);

        if($this->DailyTasks->delete($dailyTask)) {
			$this->Flash->success('The Tasks has been deleted');
		} else {
			$this->Flash->error('The Tasks could not be deleted try again');
		}
		return $this->redirect(['action'=>'index']);
	}
}

www/src/Template/DailyTasks/assign.ctp
<div class="row">
	<div class="col-xs-12 col-sm-12 col-md-12">
		<div class="box box-block bg-white">
			<div class="row">
				<div class="col-md-8">
					<h4><?php echo $title_for_layout; ?></h4>	
				</div>
			</div>
		</div>
	</div>
</div>
<div class="box box-block bg-white">
	<legend>Task</legend>						
		 <div class="row">                                           
			<div class="col-sm-4">
				<strong>Project No:</strong> <?php echo $projectTasks['project']['project_no'];	?>
			</div>
			<div class="col-sm-4">
				<strong>Project Date:</strong> <?php echo $projectTasks['project']['project_date'];	?>
			</div>
		</div><br>
        <div class="row">                                           
			<div class="col-sm-4">
				<strong>Fees Type:</strong> <?php echo $projectTasks['fees_type'];	?>
			</div>
			<div class="col-sm-4">
				<strong>Days Require:</strong> <?php echo $projectTasks['days_require'];	?>
			</div>
		</div><br>
        <div class="row">                                           
			<div class="col-sm-4">
				<strong>List Order:</strong> <?php echo $projectTasks['list_order'];	?>
			</div>
			<div class="col-sm-4">
				<strong>Percentage:</strong> <?php echo $projectTasks['percentage'];	?>
			</div>
            <div class="col-sm-4">
				<strong>Fees:</strong> <?php echo $projectTasks['fees'];	?>
			</div>
		</div><br>
		<div class="row">                                           
			<div class="col-sm-4">
				<strong>Service:</strong> <?php echo $projectTasks['service'];	?>
			</div>
			<div class="col-sm-4">
				<strong>Description:</strong> <?php echo $projectTasks['description'];	?>
			</div>
			
		</div><br>
		
	</div>
<?php echo $this->Form->create('projectTasks',array('type'=>'file','noValidate'=>true)); ?>
	<div class="box box-block bg-white">
		 <div class="row">                                           
			<div class="col-sm-4">
				<?php
                //debug($employees->toArray());exit;
					echo $this->Form->hidden('id');
					echo $this->Form->control('task_id',array('value'=>$TaskId,'type'=>'hidden'));
				    echo $this->Form->control('assigned_to',['options'=>$employees,'empty'=>'---']); 
				?>
			</div>
			<div class="col-sm-4">
				<?php echo $this->N->datepicker('target_date'); ?>
           </div>
		</div>
	</div>
	<div class="box box-block bg-white">
		<div class="row">
			<div class="col-md-12">
				<div class="pull-right">
                    <?= $this->N->cancelLink(['action'=>'index']); ?>
                    <button class="btn btn-primary">Save</button>
				</div>
			</div>
		</div>		
	</div>
<?php echo $this->Form->end(); ?>

www/src/Template/DailyTasks/edit.ctp
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Package $package
 */
?>
<div class="box box-block bg-white">
	<div class="clearfix mb-1">
		<h5 class="float-xs-left"><?= $title_for_layout; ?></h5>
	</div>
    <?= $this->Form->create($dailyTask,['type'=>'file','novalidate'=>true]) ?>
    <fieldset>
		<div class="row">
			<div class="col-md-3">
				<?php echo $this->Form->hidden('id'); ?>
				<?php echo $this->N->select2('project_id',['empty'=>'=== No Project Linked ===']); ?>
			</div>
			<div class="col-md-9">
                <?php echo $this->N->select2('activity_id',['empty'=>false]); ?>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<?php echo $this->Form->control('description', ['type'=>'textarea']); ?>
			</div>
		</div>
		<div class="row">
			<div class="col-md-3">
				<?php echo $this->Form->control('assigned_to',['options'=>$employees, 'empty'=>'---']); ?>
			</div>
			<div class="col-md-3">
				<?php echo $this->N->datepicker('due_date', ['required'=>true]); ?>
			</div>
        </div>
        <?php if(!$dailyTask->isNew()) { ?>
        <div class="row">
            <div class="col-md-3">
				<?php echo $this->N->datepicker('done_date', ['required'=>true]); ?>
			</div>
			<div class="col-md-3">
				<?php echo $this->Form->control('duration', ['options'=>range(0,12,0.5)]); ?>
			</div>
			<div class="col-md-3">
				<?php echo $this->Form->control('status', ['options'=>['Open'=>'Open', 'In Progress'=>'In Progress', 'Done'=>'Done']]); ?>
			</div>
		</div>
        <?php } ?>
	</fieldset><br>
	<fieldset>
		<div class="row pull-right">
			<div class="col-md-12">
				<?= $this->N->cancelLink(['action'=>'index']); ?>
                <?php if($dailyTask->isNew()) { ?>
				<button class="btn btn-primary">Save</button>
                <?php } ?>
			</div>
		</div>
	</fieldset><br>
	<?= $this->Form->end(); ?>
</div>

www/src/Template/DailyTasks/index.ctp
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Package[]|\Cake\Collection\CollectionInterface $packages
 */
?>

<div class="box box-block bg-white">
	<div class="clearfix mb-1">
		<h5 class="float-xs-left"><?= $title_for_layout; ?></h5>
	</div>
    <?php echo $this->Form->create(null, ['class'=>'form-inline','valueSources' => 'query','id'=>'SearchForm']); ?>
        <?php echo $this->Form->input('search',['placeholder'=>'Search','label'=>false]); ?>
        <?php echo $this->Form->button('Search', ['class'=>'btn btn-bordered-info']); ?>
        <?php echo $this->Html->link('Reset', ['action' => 'index'],['class'=>'btn btn-primary']); ?>
        <?php echo $this->Form->end(); ?>
	<script>
		$(document).ready(function(){
			$("#SearchForm").one("submit", function(e) {
				e.preventDefault();
				$.post('DailyTasks', $('#SearchForm').serialize()).done(function(data){
					NProgress.start();
					$("#ajaxDiv").empty().append(data);
					NProgress.done();
				});;
			});
		});
	</script>
</div>
<div class="box box-block bg-white">
    <div class="clearfix mb-1">
		<div class="float-xs-right">
			<?= $this->N->addLink(array('action'=>'edit')); ?>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<div class="table-responsive">
				<table class="table table-hover">
                    <thead>
                        <tr>
                            <th scope="col"><?= $this->Paginator->sort('project_id','Project No')?></th>
							<th scope="col"><?= $this->Paginator->sort('activity_id')?></th>
                            <th scope="col"><?= $this->Paginator->sort('description')?></th>
							<th scope="col"><?= $this->Paginator->sort('assigned_to','Assigned To') ?></th>
							<th scope="col"><?= $this->Paginator->sort('due_date') ?></th>
                            <th scope="col"><?= $this->Paginator->sort('duration') ?></th>
                            <th scope="col"><?= $this->Paginator->sort('done_date') ?></th>
                            <th scope="col"><?= $this->Paginator->sort('status') ?></th>
						    <th scope="col" width="15%"><?= $this->Paginator->sort('Actions') ?></th>
				        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($dailyTasks as $dailyTask): ?>
                        <tr>
                            <td><?= $dailyTask->project ? $dailyTask->project->project_no . ' ' . $dailyTask->project->client->client_name : '---'; ?></td>
							<td><?= $dailyTask->activity->activity?></td>
                            <td><?= $dailyTask->description?></td>
                            <td><span class="tag tag-info"><?= $dailyTask->assigned_employee->name?></span></td>
                            <td><?= $dailyTask->due_date; ?></td>
                            <td><?= $dailyTask->duration; ?></td>
							<td><?= $dailyTask->done_date; ?></td>
                            <td>
                                <?php
                                    if($dailyTask->status == 'Open') {
                                        echo "<span class='tag tag-success'>Open</span>";
                                    } elseif($dailyTask->status == 'In Progress') {
                                        echo "<span class='tag tag-warning'>In Progress</span>";
                                    } else {
                                        echo "<span class='tag tag-danger'>Done</span>";
                                    }
                                ?>
                            </td>
							<td class="actions">
								<?php
                                    if($dailyTask->status == 'Open') {
                                        echo $this->Html->link('Progress',['controller'=>'DailyTasks','action'=>'progress', $dailyTask->id], ['class'=>'btn btn-primary btn-sm']);
                                    }
                                ?>
                                <?= $this->N->editLink(['action' => 'edit', $dailyTask->id]); ?>
                                <?php //$this->N->deleteLink(['action' => 'delete', $dailyTask->id]); ?>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
				</table>
			</div>
       </div>
	</div>
</div>
<?php echo $this->element('Neptune.pagination'); ?>

www/src/Template/DailyTasks/progress.ctp
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Package $package
 */
?>
<div class="box box-block bg-white">
	<div class="clearfix mb-1">
		<h5 class="float-xs-left"><?= $title_for_layout; ?></h5>
	</div>
    <?= $this->Form->create($dailyTask,['type'=>'file','novalidate'=>true]) ?>
    <fieldset>
		<div class="row">
			<div class="col-md-3">
				<?php echo $this->Form->hidden('id'); ?>
				<?php echo $this->Form->control('project',['type'=>'text', 'readonly'=>'true', 'value'=> $dailyTask->project ? $dailyTask->project->project_no : '---']); ?>
			</div>
			<div class="col-md-9">
                <?php echo $this->Form->control('activity',['type'=>'text', 'readonly'=>'true', 'value'=>$dailyTask->activity->activity]); ?>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<?php echo $this->Form->control('description', ['type'=>'textarea']); ?>
			</div>
		</div>
		<div class="row">
			<div class="col-md-3">
                <?php echo $this->Form->control('assigned_to_employee',['type'=>'text', 'label'=>'Assigned To', 'readonly'=>'true', 'value'=>$dailyTask->assigned_employee->name]); ?>
			</div>
			<div class="col-md-3">
                <?php echo $this->Form->control('due_date', ['type'=>'text', 'readonly'=>'true']); ?>
			</div>
			<div class="col-md-3">
				<?php echo $this->Form->control('duration', ['options'=>array_combine(range(0,12,0.5), range(0,12,0.5))]); ?>
			</div>
			<div class="col-md-3">
				<?php echo $this->Form->control('status', ['options'=>['In Progress'=>'In Progress', 'Done'=>'Done']]); ?>
			</div>
        </div>
	</fieldset><br>
	<fieldset>
		<div class="row pull-right">
			<div class="col-md-12">
				<?= $this->N->cancelLink(['action'=>'index']); ?>
				<button class="btn btn-primary">Save</button>
			</div>
		</div>
	</fieldset><br>
</div>